### ISSUE TITLE
Fatal Error: Cue Handler: A TRACK type in the cue file is not recognised

### ISSUE THREAD

**Issue by zbikk** [ADBeta/psx-comBINe#6]
hey, i'm trying to combine both tracks of sotn to a single bin file, but i'm getting this error. not sure what it means and would appreciate any help!

here's the input and output:
`psx-combine Castlevania\ -\ Symphony\ of\ the\ Night\ \(USA\).cue`

`Created Directory: "psx-comBINe/"`

`Fatal Error: Cue Handler: A TRACK type in the cue file is not recognised`

and this is the cue file:
![Screenshot_20240222_125339](https://github.com/ADBeta/psx-comBINe/assets/145393776/33287f8b-69f5-454d-80a4-630d06b14d27)

**Comment by ADBeta** [comment]
Hi, Sorry to hear you're having issues.
I believe this issue is being caused by the "FLAGS DCP" lines in those entries. If you remove all of those occurrences and let me know if it fixes the issue, I can then patch the program to understand those flags.

I could not find a detailed list of all possible FLAGS or commands so I have been having to find and support each of them manually in the past. 

Best of luck

**Comment by zbikk** [comment]
that was it! i removed the dcp flags and the converter ran succesfully and the game starts up with no issues, not sure if this will help you, but i got this rom off of the no-intro myrient page.
